custom_formation.settings:
  type: config_object
  label: 'Custom Formation Settings'
  mapping:
    verbose:
      type: boolean
      label: 'Verbose'
    basename:
      type: string
      label: 'Base name'

